export type Source = { id:string; title:string; original:string; publisher:string; date:string; kind:string; topics:string[]; url:string; access:string; finding:string; use:string; limit:string; locator:string; doi?:string; extra?:string; priority?:boolean };
const source = (id:string,title:string,original:string,publisher:string,date:string,kind:string,topics:string[],url:string,access:string,finding:string,use:string,limit:string,locator:string,doi?:string,extra?:string):Source => ({id,title,original,publisher,date,kind,topics,url,access,finding,use,limit,locator,doi,extra});
export const researchedOn = '2026-09-17';
export const sources:Source[] = [
source('P01','国家为什么要求开展新污染物科普？','国务院办公厅关于印发新污染物治理行动方案的通知','国务院办公厅／生态环境部','2022-05-24','政策与背景',['综合'],'https://www.mee.gov.cn/zcwj/gwywj/202205/t20220524_983032.shtml','政策正文', '方案部署全生命周期治理，并明确要求开展科普宣传教育，引导公众科学认识环境风险。','支持研究背景及科普公共价值；优先读“三、保障措施（四）加强宣传引导”。','政策支持科普，不等于证明某个人群存在理解困难，也不等于证明交互设计有效。2025年目标属于原文件历史目标。','国办发〔2022〕15号；成文日期2022-05-04；二、行动举措；三（四）'),
source('P02','“新”不是刚刚被制造出来','生态环境部固体废物与化学品司有关负责人就《重点管控新污染物清单（2023年版）》答记者问','生态环境部','2023-01-13','政策与背景',['综合'],'https://www.mee.gov.cn/ywdt/zbft/202301/t20230113_1012751.shtml','官方问答正文','新污染物的界定与环境、健康风险及现有管理不足有关，不能只按出现年代理解。','为报告定义研究对象，区分广义议题与具体管控清单。','“新污染物”是动态范围；不要把清单当成所有污染物的完整目录。','关于概念、清单编制背景及范围的问答'),
source('P03','清单如何把议题变成具体治理对象','重点管控新污染物清单（2023年版）','生态环境部等六部门','2022-12-30','政策与背景',['综合','PFAS','抗生素'],'https://www.mee.gov.cn/gzk/gz/202212/t20221230_1009192.shtml','清单正文','清单按具体物质或物质类别列出环境风险管控措施，包含部分全氟化合物与抗生素。','选定一种物质后，核对其名称、用途、条目和措施。','这里只收录2023年版作背景，不宣称它是截至今日所有最新管理要求；不能把14个条目理解为14种单一分子。','生态环境部令第28号；附件清单各条目'),
source('P04','常见研究对象有哪些？','生态环境部2022年3月例行新闻发布会','生态环境部','2022-03-30','政策与背景',['综合','微塑料','内分泌干扰物','抗生素','POPs'],'https://www.mee.gov.cn/ywdt/xwfb/202203/t20220330_973154.shtml','发布会正文','发布会介绍持久性有机污染物、内分泌干扰物、抗生素、微塑料等受到关注的类别。','用作范围地图，再挑一个具体对象深入。','这些名称依据不同属性划分，并非互斥分类；PFAS中的部分物质也属于受控POPs。','新污染物治理相关问答'),
source('P05','2026年的治理背景补充','生态环境部部长黄润秋在2026年全国生态环境保护工作会议上的工作报告','生态环境部','2026-01-27','政策与背景',['综合'],'https://www.mee.gov.cn/xxgk/hjyw/202601/t20260127_1142657.shtml','官方发布页／检索摘要','报告回顾化学物质信息调查、优先控制化学品名录及新污染物治理试点等工作。','补充2026年背景线索，正式引用前定位原文段落。','本次正文提取不完整；不依据这一条断言某项政策已全部落实。','2025年工作回顾与2026年重点任务'),
source('S01','先用一个整体框架理解新污染物','Emerging contaminants: A One Health perspective','Wang F. et al.｜The Innovation','2024','科学报告与综述',['综合'],'https://pubmed.ncbi.nlm.nih.gov/38756954/','PubMed摘要与图注','综述从人、动物与环境共同健康的角度讨论新污染物来源、影响、监测和治理。','帮助绘制“来源—环境—接触对象—治理”的关系图；沿参考文献深入。','本次未核读完整综述；One Health是分析视角，不是证明你的网站有效的理论证据。','摘要；图1说明', '10.1016/j.xinn.2024.100612'),
source('S02','微塑料健康问题，哪些仍不确定？','Dietary and inhalation exposure to nano- and microplastic particles and potential implications for human health','世界卫生组织 WHO','2022-08-30','科学报告与综述',['微塑料'],'https://www.who.int/publications/i/item/9789240054608','官方报告概要','WHO汇总截至2021年12月的数据，讨论经食物、水和空气的暴露，并识别研究需求与不确定性。','把“已知、尚不明确、需要更多证据”分开呈现。','概要不是154页报告的完整核读；历史证据截止时间不能冒充2026年最终结论。','Overview；ISBN 9789240054608'),
source('S03','微塑料研究二十年：进一步精读入口','Twenty years of microplastic pollution research—what have we learned?','Science','2024','待精读线索',['微塑料'],'https://doi.org/10.1126/science.adl2746','出版方检索记录；全文待核','已核到论文题名与DOI；适合作为微塑料领域综述的下一步阅读对象。','补充WHO旧报告之后的研究脉络。','本次未获取全文，不将其具体结论写入论证。','出版方题录','10.1126/science.adl2746'),
source('S04','塑料颗粒与塑料里的化学物质不同','Chemicals in plastics','联合国环境规划署 UNEP','2023年报告／专题页','科学报告与综述',['微塑料','内分泌干扰物'],'https://www.unep.org/topics/chemicals-and-pollution-action/plastic-pollution/chemicals-plastics','官方专题页与报告介绍','塑料相关问题还涉及聚合物、添加剂与非有意添加物。颗粒污染与化学物质问题相关，却不应混为一谈。','为科普设计建立概念分层，避免把微塑料、双酚A、PFAS画成同一种东西。','未逐页核读所链接技术报告；不能从材料类别直接推定某款产品的风险。','Chemicals: an integral part of plastics'),
source('S05','PFAS是一大类物质，证据不能一概而论','Our Current Understanding of the Human Health and Environmental Risks of PFAS','美国环境保护署 EPA','动态网页','科学报告与综述',['PFAS'],'https://www.epa.gov/pfas/our-current-understanding-human-health-and-environmental-risks-pfas','官方网页正文','介绍PFAS的多种暴露路径，区分部分已知健康证据与仍在研究的问题。','支持“具体物质＋暴露情境＋证据强度”的信息结构。','美国情境不能直接换算成中国风险；不同PFAS证据不同，不应笼统说全都具有同等危害。','Exposure to PFAS May be Harmful；Additional Health Effects are Difficult to Determine'),
source('S06','“致癌分类”不是个人患癌概率','IARC Monographs evaluate the carcinogenicity of PFOA and PFOS: Questions and Answers','国际癌症研究机构 IARC','2023-11','科学报告与综述',['PFAS','传播方法'],'https://www.iarc.who.int/wp-content/uploads/2023/11/QA_Mono135.pdf','官方问答PDF正文','问答解释PFOA和PFOS评估，并说明分类反映致癌证据强度，不直接表示不同暴露水平下的风险大小。','可用来设计“危害—暴露—风险”的辨析任务。','不能据分类判断读者必然患病，也不能把两种物质的结论套到所有PFAS。','PDF第4页／问题10：classification与risk的区别'),
source('S07','内分泌干扰物在干扰什么？','Endocrine Disruptors','美国国家环境健康科学研究所 NIEHS','动态网页','科学报告与综述',['内分泌干扰物'],'https://www.niehs.nih.gov/health/topics/agents/endocrine','官方网页正文','用激素信号说明某些化学物质可能模拟、阻断或干扰内分泌系统，并介绍接触来源。','为“看不见的机制”寻找解释模型。','机制类比需要专业核验；不能把某类日用品等同于确定有害的具体产品。','Introduction；The Endocrine System；How Do We Encounter These Chemicals?'),
source('S08','POPs为什么会跨越时间与空间？','The POPs','斯德哥尔摩公约秘书处','动态网页','科学报告与综述',['POPs','综合'],'https://pops.int/TheConvention/ThePOPs/tabid/673/Default.aspx','公约官网说明','持久性有机污染物具有环境持久性、远距离迁移、生物累积等值得关注的特征。','帮助解释“排放地点”和“影响地点”可能分离。','不是全部新污染物都满足POPs的特征；列入公约的具体物质需逐一核对。','What are POPs?／公约污染物说明'),
source('S09','抗生素问题为什么也涉及环境？','Bracing for Superbugs: Strengthening environmental action in the One Health response to antimicrobial resistance','联合国环境规划署 UNEP','2023','科学报告与综述',['抗生素'],'https://www.unep.org/resources/superbugs/environmental-action','官方报告概要','报告把制药、农业与食品、医疗及污水废物链条纳入抗微生物药物耐药性问题。','把个体用药知识扩展成环境路径与多方责任的系统图。','本次核读报告概要；抗生素残留、耐药菌和耐药基因不是同一个概念，不能把耐药说成人体产生耐受。','报告介绍；三类经济部门及其价值链'),
source('S10','治理责任不能只推给个人','Guidance on wastewater and solid waste management for manufacturing of antibiotics','世界卫生组织 WHO','2024-09-03','科学报告与综述',['抗生素'],'https://www.who.int/publications/i/item/9789240097254','官方指南概要','指南关注抗生素生产环节的废水和固废管理，面向监管、采购、生产等机构。','将工业源头治理加入科普，区分个人、企业和公共部门能做什么。','概要核读，未审阅技术限值；不要据此给出用药或地方排放合规建议。','Overview；Target audiences；ISBN 9789240097254'),
source('E01','听过PFAS，不代表知道它是什么','Let’s talk about PFAS: Inconsistent public awareness about PFAS and its sources in the United States','Berthold TA, McCrary A, deVilleneuve S, Schramm M｜PLOS ONE','2023-11-16','公众认知研究',['PFAS'],'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0294134','全文：摘要、方法、结果与局限','2023年4月美国成人在线调查，1100人，配额并加权。45.1%表示没听过且不知道是什么，31.6%听过但不知道是什么。','问卷应区分听说、自评知识和实际理解；可参考附录题目。','横断面、自报数据，不能推出科普因果效果；这些比例不是中国公众现状，也不是水样检测结果。','Methods / Survey instrument；Results / Table 2','10.1371/journal.pone.0294134'),
source('E02','“担心污染”与“理解来源”可能分离','What does the public think about microplastics? Insights from an empirical analysis of mental models elicited through free associations','Felipe-Rodriguez M, Böhm G, Doran R｜Frontiers in Psychology','2022-08-03','公众认知研究',['微塑料','传播方法'],'https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2022.920454/full','全文：摘要与研究框架','挪威成人样本2720人，用自由联想编码分析。联想常涉及海洋污染和动物伤害，对来源、解决方式的自发提及较少。','可借鉴先自由描述、再画路径图的探索方法，寻找知识关系的缺口。','挪威样本不能代表中国；没有自发提及不等于完全不知道。','Abstract；Introduction（mental models与free associations）','10.3389/fpsyg.2022.920454'),
source('E03','上海微塑料认知研究：优先补齐全文','Public attitudes towards microplastics: Perceptions, behaviors and policy implications','Deng L. et al.｜Resources, Conservation and Recycling','2020','待精读线索',['微塑料'],'https://doi.org/10.1016/j.resconrec.2020.105096','出版方检索记录；全文待核','已找到中国语境的相关实证研究题录，涉及微塑料态度与减排意愿。','优先通过学校数据库获取全文，核实上海样本、抽样方法、调查时间和量表。','本次不采用其被转述的认知比例；完成方法核读之前不外推到当前目标受众。','卷163，文章105096；样本方法待核','10.1016/j.resconrec.2020.105096'),
source('E04','网站讲了威胁，有没有讲清行动？','Efficacy and Threat Language in PFAS Messaging','Hutchins RA et al.｜Risk Analysis','2026-03-31','公众认知研究',['PFAS','传播方法'],'https://onlinelibrary.wiley.com/doi/abs/10.1111/risa.70239','论文摘要＋学会研究说明','研究结合内容分析和计算语言分析，发现网站对威胁与应对效能的表达存在差异，整体对效能信息强调不足。学会说明分析了98个美国搜索相关网站。','适合建立案例评价表：风险解释、可执行行动、信息入口、证据与不确定性。','这是网站内容分析，不是用户效果实验；98站点信息来自学会说明，不能推断所有中国网站如此。','Abstract；SRA 2026-04-08研究说明','10.1111/risa.70239','https://www.sra.org/2026/04/08/new-study-reveals-online-pfas-information-from-public-sources-can-fall-short-and-leave-public-without-enough-guidance/'),
source('M01','如实表达不确定性，会让人不信任吗？','The effects of communicating uncertainty on public trust in facts and numbers','van der Bles AM et al.｜PNAS','2020','传播方法',['传播方法'],'https://pmc.ncbi.nlm.nih.gov/articles/PMC7149229/','全文：研究意义与摘要','五项实验共5780人，比较不同不确定性表达。信任下降总体较小，主要出现在语言表述条件，数字范围的影响较小。','为“已知／未知”分层与范围表达提供方法参考，并设计自己的理解测试。','研究涉及气候、统计等主题，不是新污染物实验；不能推断任何不确定性设计都会增进信任。','Significance；Abstract','10.1073/pnas.1913678117'),
source('M02','故事可以帮助解释，也会影响判断','Using narratives and storytelling to communicate science with nonexpert audiences','Dahlstrom MF｜PNAS','2014','待精读线索',['传播方法'],'https://doi.org/10.1073/pnas.1320645111','出版方检索摘要；全文待核','文章讨论叙事在面向非专业受众的科学传播中的作用及伦理问题。','为情境叙事方案补理论阅读，同时关注个案代表性。','不能把某个故事当作总体证据，不能仅凭此文断言游戏或故事比图文有效。','出版方摘要／正文待精读','10.1073/pnas.1320645111'),
source('C01','按读者问题组织科普入口','PFAS Explained','美国环境保护署 EPA','动态网页','传播与数据案例',['PFAS','传播方法'],'https://www.epa.gov/pfas/pfas-explained','网页内容结构','以基础解释及相关问答帮助读者进入PFAS议题，并连接进一步信息。','案例观察：使用读者的问题作为信息导航，而非只按化学分类。','本次分析内容结构，未做真实用户可用性测试；不能移植美国监管与生活建议为中国结论。','PFAS Explained 页面及链接组织'),
source('C02','同一套知识如何适配多种传播媒介？','PFAS Communications Toolkit','美国环境保护署 EPA','页面更新2026-04-07','传播与数据案例',['PFAS','传播方法'],'https://www.epa.gov/sdwa/pfas-communications-toolkit','工具包目录正文','提供视频、社交媒体材料、信息图、问答、事实说明和沟通提示。','案例观察：先构建可复用内容，再按受众与场景选择媒介。','本次核读目录，未逐一评估素材；存在工具包不等于其效果已被验证，法规内容具有美国情境。','Videos / Infographics / Questions and Answers / Fact Sheets'),
source('C03','微塑料数据怎样成为可探索的地图？','Marine Microplastics','NOAA国家环境信息中心 NCEI','动态数据库','传播与数据案例',['微塑料','传播方法'],'https://www.ncei.noaa.gov/products/microplastics','产品说明与数据字段','提供地图与数据访问，记录采样日期、地点、方法、滤网尺寸、浓度及单位等元数据。','案例观察：数据图需要同时交代采样条件；可以分析筛选和溯源如何帮助理解。','海洋观测点不是全世界均匀采样；空白位置不等于无污染，不同单位不能随意直接比较。','Data Access；Data submissions must include'),
source('C04','地图筛选有哪些现成的交互参考？','Marine Microplastics Map Tutorial','NOAA国家环境信息中心 NCEI','动态教程','传播与数据案例',['微塑料','传播方法'],'https://www.ncei.noaa.gov/products/microplastics/help','官方教程检索内容','教程介绍用地图查看、筛选和下载数据库记录。','作为C03的配套操作资料，研究筛选条件如何向读者解释数据范围。','是同一案例的配套资料，不能当成另一项独立科学证据；未开展现场交互评测。','Marine Microplastics Map Tutorial'),
source('C05','国内已经有哪些科普实践？','2026年生态环境科技活动周主场开放活动在京举行','生态环境部','2026-05-31','传播与数据案例',['综合','传播方法'],'https://www.mee.gov.cn/ywgz/kjycw/sthjkjcx/sthjkp/hjkpdt/202605/t20260531_1157290.shtml','官方活动报道／检索摘要','报道的科普展览覆盖新污染物治理等领域，并结合讲座和科研平台开放。','提醒选题要比较已有实践，不能把“尚未搜全”写成“国内没有科普”。','报道不能证明受众学习效果；尚未获取具体展项和观众评价，需要进一步案例调研。','北京主会场活动介绍'),
];
const firstReads = new Set(['P01','P02','S02','E01','E02','E04']);
sources.forEach(s => { s.priority = firstReads.has(s.id); });
export const topics = ['全部','综合','微塑料','PFAS','抗生素','内分泌干扰物','POPs','传播方法'];
export const kinds = ['全部','政策与背景','科学报告与综述','公众认知研究','传播方法','传播与数据案例','待精读线索'];
