import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, Download, Search, BookOpen } from 'lucide-react';
import { sources, topics, kinds, researchedOn } from './researchData';
import './research-library.css';
const pathways = [
  {name:'微塑料',question:'一件塑料制品，如何变成环境中的小颗粒？',stages:['生产与使用塑料','磨损、破碎或颗粒释放','在水、空气、土壤中迁移','生物或人经不同途径接触','结合粒径、剂量等评估影响'],note:'这是一张概念路径图，不是某件产品的排放或健康风险计算。塑料颗粒与添加剂需要分开解释。',refs:['S02','S04','C03']},
  {name:'PFAS',question:'为何污染源和人接触到它的地方可能不同？',stages:['某些工业与产品用途','生产、使用或处置释放','随水等介质迁移与持续存在','食物、水、粉尘等暴露途径','按具体物质与暴露评价风险'],note:'PFAS是物质家族，不能用PFOA的研究结论替代所有PFAS的证据。',refs:['S05','S06']},
  {name:'抗生素',question:'药物从生产和使用到环境，会经过哪些环节？',stages:['制药、医疗或养殖等环节','废水与废物排放','残留与环境微生物相互作用','耐药性发展和传播的环境路径','联合源头、过程与末端治理'],note:'此处解释环境与耐药性关系，不提供用药建议。“抗生素残留”“耐药菌”“耐药基因”需要分别定义。',refs:['S09','S10']},
  {name:'内分泌干扰物',question:'“干扰激素信号”意味着什么？',stages:['具体化学物质及其用途','产品或环境中的释放与迁移','经食物、水、空气等接触','可能模拟、阻断或干扰激素作用','结合物质、剂量和时段分析'],note:'这是机制示意，不是个人诊断。不能从“某类产品可能含有”跳到“这件产品必然有害”。',refs:['S07','S04']},
];
const chains = [
  {title:'议题有公共价值',status:'已有依据',because:'国家明确部署治理与科普宣传；科学资料提供具体内容边界。',therefore:'可以开展新污染物科普方向的研究。',missing:'仍需缩小到一个对象、一个人群和一种理解问题。',refs:['P01','P02']},
  {title:'传播可能存在理解障碍',status:'已有外部研究',because:'已有研究发现“听说过”和“理解来源”并不相同，部分网站对行动信息强调不足。',therefore:'值得在你的目标受众中检查这些问题是否存在。',missing:'国外研究不能代替你的用户调研；中国相关全文也需补齐。',refs:['E01','E02','E03','E04']},
  {title:'设计为何有必要',status:'待一手调研',because:'如果观察到用户无法连接来源、迁移与暴露，或混淆检出与风险……',therefore:'才有依据尝试路径可视化、证据分层或有反馈的理解任务。',missing:'需要真实任务记录与现有材料比较；这里是设计推论，不是已有结论。',refs:['S06','M01']},
  {title:'为什么选择交互',status:'待原型比较',because:'如果交互能让用户检验判断并获得针对性反馈……',therefore:'可与内容等量的图文版本比较，验证理解是否改善。',missing:'优先测路径解释、概念辨别、迁移应用；好看、满意、停留时间不能单独证明有效。',refs:[]},
];
const directions = [
  {name:'微塑料 · 来源与路径理解',fit:'优先做探索调研',question:'路径可视化与反馈任务，能否帮助非环境专业学生解释微塑料的来源及迁移？',why:'已有心理模型研究与公开数据案例，可将理解困难落实为具体任务。',task:'先让受访者自由联想，再画“从哪里来、到哪里去”的图，追问每条箭头。',design:'根据真实缺口制作路径交互；用未见过的场景检验能否迁移解释。',risk:'容易变成泛泛的塑料环保宣传；必须说明哪些内容特属于微塑料。',refs:['E02','S02','C03']},
  {name:'PFAS · 风险信息与证据理解',fit:'论证线索较直接',question:'分层呈现已知、未知与行动信息，能否改善读者对PFAS风险信息的理解？',why:'已有认知调查和网站内容分析，能直接连接到信息组织问题。',task:'让受访者阅读同一段真实材料，解释“检出”“风险”与下一步想查什么。',design:'制作带来源、时效和证据边界的材料；比较误解率与信息查找任务。',risk:'科学内容门槛较高，需专业核验；不能变成个人健康风险打分器。',refs:['E01','E04','S06','M01']},
  {name:'抗生素 · 环境路径与责任理解',fit:'适合系统关系表达',question:'系统图能否帮助受众理解抗生素环境排放与耐药性之间的联系及多方责任？',why:'WHO、UNEP已有清晰的生产与环境治理框架。',task:'请受访者解释“耐药的是谁”，再区分个人、生产者与治理机构能做的事。',design:'用关系图和角色任务解释环境链条；测机制与责任归属的变化。',risk:'不要滑向泛用药科普；环境机制必须准确，并控制内容范围。',refs:['S09','S10']},
];
function exportLibrary() {
  const text = `# 新污染物研究资料库\n\n整理日期：${researchedOn}\n初步范围调研，非系统综述。中文标题为阅读提示。资料卡明确核读范围；设计启发不是研究结论。\n\n` + sources.map(s => `## [${s.id}] ${s.title}\n\n${s.original}\n${s.publisher}｜${s.date}\n类型：${s.kind}｜主题：${s.topics.join('、')}\n核读范围：${s.access}\n原文：${s.url}\n${s.doi ? `DOI：${s.doi}\n` : ''}${s.extra ? `补充出处：${s.extra}\n` : ''}\n要点：${s.finding}\n\n开题用途／整理者建议：${s.use}\n\n不能说明：${s.limit}\n\n原文定位：${s.locator}\n`).join('\n');
  const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'})); const a=document.createElement('a');a.href=url;a.download=`新污染物研究资料库-${researchedOn}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function ResearchLibrary(){
 const [section,setSection]=useState('start'); const [path,setPath]=useState(0); const [query,setQuery]=useState(''); const [topic,setTopic]=useState('全部'); const [kind,setKind]=useState('全部'); const [priority,setPriority]=useState(false); const [selected,setSelected]=useState('');
 useEffect(()=>{document.documentElement.classList.add('research-library-mode');document.body.classList.add('research-library-mode');const old=document.title;document.title='新污染物 · 研究资料库 | GemosDodo';window.scrollTo(0,0);return()=>{document.title=old;document.documentElement.classList.remove('research-library-mode');document.body.classList.remove('research-library-mode');};},[]);
 useEffect(()=>{if(section==='library'&&selected){requestAnimationFrame(()=>document.getElementById('source-'+selected)?.scrollIntoView({block:'center',behavior:'auto'}));}},[section,selected]);
 const filtered=useMemo(()=>sources.filter(s=>(topic==='全部'||s.topics.includes(topic))&&(kind==='全部'||s.kind===kind)&&(!priority||s.priority)&&`${s.id} ${s.title} ${s.original} ${s.publisher} ${s.finding} ${s.topics.join(' ')} ${s.doi||''}`.toLowerCase().includes(query.trim().toLowerCase())),[topic,kind,priority,query]);
 const openSource=(id:string)=>{setTopic('全部');setKind('全部');setPriority(false);setQuery('');setSelected(id);setSection('library'); if(section==='library')requestAnimationFrame(()=>document.getElementById('source-'+id)?.scrollIntoView({block:'center'}));};
 const refs=(ids:string[])=><div className="rl-refs">{ids.map(id=><button key={id} onClick={()=>openSource(id)} title={sources.find(s=>s.id===id)?.title}>[{id}] {sources.find(s=>s.id===id)?.title}</button>)}</div>;
 const navigate=(id:string)=>{setSection(id);setSelected('');window.scrollTo(0,0);};
 return <div className="rl-page no-grass" lang="zh-CN"><header className="rl-header"><Link to="/graduation"><ArrowLeft size={16}/>研究工作台</Link><span>毕业设计 / 阅读档案</span><Link to="/graduation/review">导师阅览版<ArrowUpRight size={15}/></Link></header>
 <main className="rl-main"><section className="rl-hero"><div><p className="rl-kicker">RESEARCH NOTES · 01</p><h1>先看懂新污染物，<br/>再找到设计的理由。</h1><p>从科学事实到理解问题。把资料读成一条有依据的研究线索。</p></div><aside><strong>{sources.length}<small>份资料与阅读线索</small></strong><span>中文导读 · 原文可追溯</span><span>整理于 {researchedOn}</span><button onClick={exportLibrary}><Download size={15}/>导出全部阅读笔记</button></aside></section>
 <nav className="rl-nav" aria-label="资料库栏目">{[['start','01','先看懂'],['argument','02','选题怎么立'],['cases','03','看已有实践'],['library','04','全部资料']].map(([id,n,label])=><button key={id} onClick={()=>navigate(id)} aria-pressed={section===id} className={section===id?'active':''}><small>{n}</small>{label}</button>)}</nav>
 {section==='start'&&<div className="rl-content"><section className="rl-lede"><span className="rl-label">先抓住这件事</span><h2>“新”，更多关乎认识与管理的变化。</h2><p>一些物质已使用多年，但其环境风险逐渐受到关注，现有管理仍需完善。你的科普对象可以是其中一种物质、某条环境路径，或人们理解这些信息时遇到的具体问题。</p>{refs(['P02','S01'])}</section>
 <div className="rl-grid three">{[['不是一张互斥分类表','微塑料按颗粒特征讨论，内分泌干扰物按作用机制讨论，POPs强调持久性等特征。它们的分类角度不同，部分范围会交叠。',['P04','S07','S08']],['检出，不等于已确定个人风险','检测回答是否发现及发现多少；风险判断还涉及物质性质、接触途径、剂量、时间和证据。不应直接从“存在”跳到“必然伤害”。',['S05','S06']],['“尚不确定”也不是“可以不管”','科学边界和治理行动可以同时说明。准确科普应告诉读者证据支持到哪里，以及还缺什么，而不是在恐慌和无害之间二选一。',['S02','P01']]].map(([title,body,ids])=><article className="rl-card" key={title as string}><h3>{title as string}</h3><p>{body as string}</p>{refs(ids as string[])}</article>)}</div>
 <section className="rl-section"><div className="rl-section-title"><div><span className="rl-label">把知识连起来</span><h2>从来源，到环境，再到影响</h2></div><span>概念示意 · 非风险计算</span></div><div className="rl-pills" aria-label="切换污染物路径">{pathways.map((p,i)=><button key={p.name} aria-pressed={path===i} onClick={()=>setPath(i)}>{p.name}</button>)}</div><div className="rl-pathway"><h3>{pathways[path].question}</h3><ol>{pathways[path].stages.map((s,i)=><li key={s}><span>0{i+1}</span><p>{s}</p></li>)}</ol><p className="rl-muted">{pathways[path].note}</p>{refs(pathways[path].refs)}</div></section>
 <section className="rl-section"><span className="rl-label">第一次阅读，从这六份开始</span><h2>带着问题读，比堆收藏更有用</h2><div className="rl-reading">{sources.filter(s=>s.priority).map((s,i)=><button key={s.id} onClick={()=>openSource(s.id)}><span>0{i+1}</span><div><h3>{s.title}</h3><p>{s.publisher} · {s.date}</p></div><ArrowUpRight size={18}/></button>)}</div></section><div className="rl-note"><strong>目前可以成立的判断</strong><p>这个方向有政策与科学背景，也存在可参考的传播研究。你的具体设计必要性，还需要由目标受众的真实困难、已有材料的不足，以及原型测试共同支撑。</p><button onClick={()=>navigate('argument')}>继续看：因为什么，所以做什么 →</button></div></div>}
 {section==='argument'&&<div className="rl-content"><section className="rl-lede"><span className="rl-label">导师最关心的问题</span><h2>重要的议题，怎样变成成立的设计研究？</h2><p>把“为什么值得关注”和“为什么需要我的设计”分开论证。下面清楚标出了已有依据和仍待验证的环节。</p></section><div className="rl-chain">{chains.map((c,i)=><article key={c.title}><div className="rl-chain-head"><span>0{i+1}</span><h3>{c.title}</h3><em>{c.status}</em></div><div className="rl-grid"><p><b>因为</b>{c.because}</p><p><b>所以</b>{c.therefore}</p></div><p className="rl-boundary">还差什么：{c.missing}</p>{refs(c.refs)}</article>)}</div><section className="rl-section"><span className="rl-label">整理者提出的候选方向 · 尚未定题</span><h2>先比较三个可验证的问题</h2><p className="rl-muted">下面是基于资料的设计推论，不是论文已证实的结论。以非环境专业学生为起点只是招募可行性假设，需与你的资源和导师意见核对。</p><div className="rl-grid three">{directions.map(d=><article className="rl-card" key={d.name}><span className="rl-label">{d.fit}</span><h3>{d.name}</h3><p className="rl-question">{d.question}</p><dl><dt>为什么值得试</dt><dd>{d.why}</dd><dt>先怎样调查</dt><dd>{d.task}</dd><dt>怎样设计与验证</dt><dd>{d.design}</dd><dt>控制边界</dt><dd>{d.risk}</dd></dl>{refs(d.refs)}</article>)}</div></section><section className="rl-note"><h3>下一轮调研，产出什么？</h3><ol><li>精读 E03 的中国样本研究，记录样本、时间、方法与局限。</li><li>选择一个候选对象，用相同维度比较 6—8 份现有科普材料。</li><li>招募可接触的目标受众，先做约 6—8 人探索访谈和理解任务；这是探索安排，不用于代表全体公众。</li><li>整理“观察到的困难 → 原始记录 → 对应设计策略 → 评价任务”，再与导师收窄题目。</li></ol><p>测试规模与统计方法应在确定研究问题后制定；现阶段没有已完成的用户调研结果。</p></section></div>}
 {section==='cases'&&<div className="rl-content"><section className="rl-lede"><span className="rl-label">已有实践，不是空白起点</span><h2>比较它们如何解释，而不只看形式。</h2><p>以下是基于公开页面的初步内容观察，尚未开展真实用户测试，也未把网站存在本身当作有效性证据。</p></section><div className="rl-grid">{[
 ['C01','问题驱动的阅读入口','先回答是什么，再引导进一步阅读。','你的受众进入页面时最想知道什么？能否在第一屏找到答案？'],
 ['C02','跨媒介的内容工具包','同一议题分成视频、信息图、问答等材料。','媒介选择对应什么使用场景？删减内容后是否仍保留证据边界？'],
 ['C03','带数据来源的探索地图','地图与数据记录连接，包含采样方法、时间和单位。','用户是否把采样空白理解成无污染？筛选后是否知道自己看的是哪一组数据？'],
 ['C05','国内科普展览与开放活动','已有面向公众的讲座、展览和科研设施开放。','需要进一步获得具体展项与反馈，才能判断还缺少什么。'],
 ].map(([id,title,observation,question])=><article className="rl-card" key={id}><span className="rl-label">{id} / 案例观察</span><h3>{title}</h3><p>{observation}</p><div className="rl-case-question"><b>你的案例分析可以问</b><p>{question}</p></div>{refs([id])}</article>)}</div><section className="rl-note"><h3>统一比较六个维度</h3><p>目标受众与情境 / 来源与路径是否清楚 / 风险与不确定性 / 信息查找难度 / 行动与多方责任 / 证据出处及更新时间。</p><p>先记录材料实际有什么，再用理解任务观察问题。避免只凭“画面不够新颖”判断它无效。</p>{refs(['E04','M01','C04'])}</section></div>}
 {section==='library'&&<div className="rl-content"><section className="rl-lede"><span className="rl-label">可追溯的阅读卡片</span><h2>每份资料，都标明能支持到哪里。</h2><p>中文标题是阅读提示，展开可查看原始题名、出处、核读范围及局限。下载的阅读笔记包含全部链接。</p></section><div className="rl-controls"><label className="rl-search"><Search size={18}/><input value={query} onChange={e=>{setQuery(e.target.value);setSelected('');}} placeholder="搜索：微塑料、认知、WHO、DOI…" aria-label="搜索资料"/></label><div className="rl-filter-row"><label>主题<select value={topic} onChange={e=>{setTopic(e.target.value);setSelected('');}}>{topics.map(t=><option key={t}>{t}</option>)}</select></label><label>资料类型<select value={kind} onChange={e=>{setKind(e.target.value);setSelected('');}}>{kinds.map(t=><option key={t}>{t}</option>)}</select></label><label className="rl-check"><input type="checkbox" checked={priority} onChange={e=>setPriority(e.target.checked)}/>只看建议先读</label><button onClick={()=>{setQuery('');setTopic('全部');setKind('全部');setPriority(false);setSelected('');}}>重置筛选</button></div></div><div className="rl-result"><span role="status">显示 {filtered.length} / {sources.length} 份</span><button onClick={exportLibrary}><Download size={15}/>导出全部</button></div><div className="rl-sources">{filtered.map(s=><details className="rl-source" key={s.id} id={'source-'+s.id} open={selected===s.id} onToggle={e=>{if(e.currentTarget.open&&selected!==s.id)setSelected(s.id);else if(!e.currentTarget.open&&selected===s.id)setSelected('');}}><summary><span className="rl-source-id">{s.id}</span><div><div className="rl-tags"><span>{s.kind}</span>{s.priority&&<span>建议先读</span>}</div><h3>{s.title}</h3><p>{s.publisher} · {s.date}</p></div><span className="rl-plus">＋</span></summary><div className="rl-source-body"><p className="rl-original">{s.original}</p><div className="rl-access"><BookOpen size={16}/><span>本次核读：{s.access}</span></div><dl><dt>读懂这一份</dt><dd>{s.finding}</dd><dt>开题用途／整理者建议</dt><dd>{s.use}</dd><dt>它不能说明什么</dt><dd>{s.limit}</dd><dt>原文定位</dt><dd>{s.locator}</dd></dl><div className="rl-source-links"><a href={s.url} target="_blank" rel="noopener noreferrer">打开原始来源<ArrowUpRight size={15}/></a>{s.extra&&<a href={s.extra} target="_blank" rel="noopener noreferrer">学会研究说明<ArrowUpRight size={15}/></a>}</div>{s.doi&&<p className="rl-doi">DOI: {s.doi}</p>}<small>链接与核读范围整理日期：{researchedOn} · {s.topics.join(' / ')}</small></div></details>)}{!filtered.length&&<p className="rl-empty">没有匹配资料。可以减少筛选条件，或尝试“风险”“PFAS”等关键词。</p>}</div></div>}
 <footer className="rl-footer"><details><summary>这份调研如何整理？有哪些还没完成？</summary><p>这是面向信息与交互设计开题的初步范围调研，非系统综述，也不声称穷尽全部文献。检索结合中文“新污染物／科普／公众认知”和英文 emerging contaminants、microplastics、PFAS、risk communication、mental models、uncertainty 等词，优先保留官方原文、期刊论文及机构资料。</p><p>收录 {sources.length} 份资料记录，其中 3 份明确列为待精读线索；C03 与 C04 属于同一案例。报告概要、论文摘要、全文段落分别标注，不把打开页面等同于完整精读。未获取学校数据库中的全部中文文献，也没有完成目标受众访谈、专家核验或设计效果实验。</p><p>资料链接与中文笔记随网站保存，不依赖当前浏览器缓存。保留原文入口，不转载整篇论文；外部页面可能更新或迁移。科学健康内容用于研究背景，不用于计算个人风险。正式开题引用需再次核对原文与学校引文格式。</p></details><div><span>GemosDodo · 研究档案 / {researchedOn}</span><button onClick={exportLibrary}>下载本轮完整阅读笔记<Download size={14}/></button></div></footer></main></div>;
}
