import { useEffect, useState } from 'react';
import { researchTimeline } from './researchTimeline';
type Row={year:number;mentions:number;total:number;per10000:number;query:string;searchUrl:string;apiUrl:string;denominatorApiUrl:string};
type Trend={retrievedAt:string;terms:string[];rows:Row[]};
export default function ResearchHistory(){
 const [data,setData]=useState<Trend|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0),[mode,setMode]=useState<'per10000'|'mentions'>('per10000'),[year,setYear]=useState(2025),[region,setRegion]=useState('全部');
 useEffect(()=>{const controller=new AbortController();setError(false);fetch('/research/literature-trend.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(!Array.isArray(d.rows)||d.rows.length!==16)throw Error();setData(d);}).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>controller.abort();},[retry]);
 const current=data?.rows.find(r=>r.year===year),rows=data?.rows||[], max=Math.max(1,...rows.map(r=>r[mode]));const top=mode==='mentions'?Math.ceil(max/200)*200:Math.ceil(max/2)*2;
 const x=(y:number)=>70+(y-2010)/15*820;const y=(n:number)=>310-n/top*250;const fmt=(n:number)=>mode==='mentions'?n.toLocaleString():n.toFixed(2);
 const years=[...new Set(researchTimeline.filter(t=>region==='全部'||t.region===region).map(t=>t.year))];
 return <div className="rl-content rh-content"><section className="rl-lede"><span className="rl-label">时间线与文献趋势</span><h2>什么时候受到关注？资料中出现得更多了吗？</h2><p>用两类证据分别回答：政策与科学报告显示议题如何发展，文献检索显示特定术语在一个数据库中出现的频率。两者都不能直接测量整个社会的重视程度。</p></section>
 <section className="rh-chart-panel"><div className="rl-section-title"><div><span className="rl-label">2010—2025 · 16个完整年份</span><h2>新污染物相关术语的文献出现趋势</h2></div><span>Europe PMC · PubMed来源记录</span></div><p className="rl-muted">检索标题或摘要中的6种英文概括性表述；命中任意一种，每条记录计一次。不是词语总出现次数，也不是全部新污染物研究总量。</p><div className="rl-pills" aria-label="切换趋势指标"><button aria-pressed={mode==='per10000'} onClick={()=>setMode('per10000')}>出现比例 · 每万条</button><button aria-pressed={mode==='mentions'} onClick={()=>setMode('mentions')}>年度命中文献数</button></div>
 {error?<p role="alert">数据暂时无法加载。<button onClick={()=>setRetry(retry+1)}>重新加载</button>，或<a href="/research/literature-trend.csv" download>下载CSV</a>查看。</p>:!data?<p role="status">正在读取已保存的统计数据…</p>:<>
 <p className="rh-chart-hint">点击数据点或选择年份查看数值；手机可左右滑动图表。</p><div className="rh-chart-scroll"><svg className="rh-chart" viewBox="0 0 940 375" role="img" aria-labelledby="rh-chart-title rh-chart-desc"><title id="rh-chart-title">2010至2025年新污染物相关术语{mode==='mentions'?'年度命中文献数':'每万条文献出现比例'}</title><desc id="rh-chart-desc">标题摘要英文关键词联合检索。数据来自Europe PMC中的PubMed来源记录。完整数值见下方表格。</desc><text x="70" y="25" className="rh-axis-title">{mode==='mentions'?'命中文献记录数（条）':'每万条PubMed来源记录中的命中数（条 / 万条）'}</text>{Array.from({length:6},(_,i)=>top*i/5).map(n=><g key={n}><line x1="70" x2="890" y1={y(n)} y2={y(n)} stroke="#dce2d9"/><text x="57" y={y(n)+4} textAnchor="end">{mode==='mentions'?Math.round(n):n.toFixed(1)}</text></g>)}<line x1="70" x2="890" y1="310" y2="310" stroke="#9bad94"/><path d={rows.map((r,i)=>`${i?'L':'M'} ${x(r.year)} ${y(r[mode])}`).join(' ')} fill="none" stroke="#42664b" strokeWidth="3"/>{rows.map(r=><g key={r.year}><text x={x(r.year)} y="335" textAnchor="middle">{r.year}</text><circle cx={x(r.year)} cy={y(r[mode])} r={r.year===year?7:4} fill={r.year===year?'#b37b3f':'#42664b'} stroke="#fff" strokeWidth="2"/><circle cx={x(r.year)} cy={y(r[mode])} r="15" fill="transparent" tabIndex={0} role="button" aria-label={`${r.year}年，${fmt(r[mode])}${mode==='mentions'?'条':'条每万条'}`} onMouseEnter={()=>setYear(r.year)} onFocus={()=>setYear(r.year)} onClick={()=>setYear(r.year)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setYear(r.year);}}}><title>{r.year}：{fmt(r[mode])}</title></circle></g>)}<text x="890" y="365" textAnchor="end">发表年份（PUB_YEAR）</text></svg></div>
 <div className="rh-year-detail" aria-live="polite"><label>查看年份<select value={year} onChange={e=>setYear(Number(e.target.value))}>{rows.map(r=><option key={r.year}>{r.year}</option>)}</select></label>{current&&<><span><strong>{current.mentions.toLocaleString()}</strong> 条命中</span><span>当年总量 <strong>{current.total.toLocaleString()}</strong> 条</span><span><strong>{current.per10000.toFixed(2)}</strong> 条 / 万条（{(current.per10000/100).toFixed(4)}%）</span><a href={current.searchUrl} target="_blank" rel="noopener noreferrer">查看该年检索 ↗</a></>}</div>
 <div className="rl-grid rh-findings"><article><span className="rl-label">长期变化</span><h3>61 → 1,274 条</h3><p>2010至2025年，命中数约为原来的 {(rows[15].mentions/rows[0].mentions).toFixed(1)} 倍；每万条出现比例从 {rows[0].per10000.toFixed(2)} 上升到 {rows[15].per10000.toFixed(2)}。</p></article><article><span className="rl-label">不要忽略不同指标的差别</span><h3>2025年：数量微增，比例回落</h3><p>2024年每万条为 {rows[14].per10000.toFixed(2)}，2025年为 {rows[15].per10000.toFixed(2)}。不能把长期增长描述成逐年上升，也不能从一年回落推断政策不再重视。</p></article></div>
 <details className="rh-method"><summary>统计口径、检索式与局限</summary><dl><dt>数据来源与范围</dt><dd>Europe PMC REST API，限定 SRC:MED（PubMed来源）。这是跨国发表记录集合，包含中国作者研究；不等于“国外文献”，也没有按作者国家分组。</dd><dt>分子</dt><dd>当年标题或摘要字段 TITLE_ABS 命中以下任一短语的记录数，OR合并去重。引号按数据库短语检索规则匹配，关闭额外同义词扩展。</dd></dl><ul>{data.terms.map(t=><li key={t}><code>{t}</code></li>)}</ul><dl><dt>分母与计算</dt><dd>同年全部 SRC:MED 记录数，未限制文献类型或必须具有摘要。每万条出现数 = 命中数 ÷ 当年全部记录数 × 10,000；百分比 = 命中数 ÷ 全部记录数 × 100%。</dd><dt>年份</dt><dd>采用数据库 PUB_YEAR；2010—2025。2026年尚未结束，未与完整年份并列。已结束年份也可能因延迟收录、元数据修订而变化。</dd><dt>检索快照</dt><dd>{data.retrievedAt}。原始API响应随网站保存；点击在线检索时，数据库结果可能已经变化。</dd><dt>不能推出什么</dt><dd>没有覆盖中文数据库、政策全文、新闻或社交媒体；不等于公众知晓率、政府重视率或污染风险。数据库偏生命科学与生物医学，也遗漏只写PFAS、微塑料等具体名称而未使用这些概括术语的文章。英文术语与中国政策“新污染物”的范围不完全相同。</dd><dt>代表性检索式（{year}年）</dt><dd><code className="rh-query">{current?.query}</code></dd></dl><p><a href="https://europepmc.org/Help" target="_blank" rel="noopener noreferrer">数据库检索说明 ↗</a> · <a href="https://www.ebi.ac.uk/europepmc/webservices/rest/fields?format=json" target="_blank" rel="noopener noreferrer">API字段表 ↗</a></p></details>
 <details className="rh-method"><summary>查看16年完整数据与逐年原始链接</summary><div className="rh-table-scroll"><table><caption>固定检索式年度统计；每万条比例由原始计数计算</caption><thead><tr><th>年份</th><th>命中数</th><th>全部记录数</th><th>每万条</th><th>原始计数</th></tr></thead><tbody>{rows.map(r=><tr key={r.year}><td>{r.year}</td><td>{r.mentions.toLocaleString()}</td><td>{r.total.toLocaleString()}</td><td>{r.per10000.toFixed(2)}</td><td><a href={r.apiUrl} target="_blank" rel="noopener noreferrer">分子 ↗</a> / <a href={r.denominatorApiUrl} target="_blank" rel="noopener noreferrer">分母 ↗</a></td></tr>)}</tbody></table></div></details></>}
 <div className="rh-downloads"><a href="/research/literature-trend.csv" download>下载数据 CSV ↓</a><a href="/research/literature-trend-raw.json" download>原始响应 JSON ↓</a><a href="/research/literature-trend.png" download>报告用图 PNG ↓</a><a href="/research/literature-trend.svg" download>矢量图 SVG ↓</a></div></section>
 <section className="rl-section"><span className="rl-label">国内外关键节点 · 精选 {researchTimeline.length} 项</span><h2>从风险认识，到专项治理，再到传播问题</h2><p className="rl-muted">按文件、报告或事件年份排列；国内外各自保留出处。2001年节点作为前史，时间线不等于完整政策年表，也不能按节点多少衡量哪个国家更重视。</p><div className="rl-pills" aria-label="时间线地区筛选">{['全部','国内','国际'].map(r=><button key={r} aria-pressed={r===region} onClick={()=>setRegion(r)}>{r==='全部'?'国内外对照':r}</button>)}</div><div className="rh-timeline">{years.map(yr=><section className="rh-time-row" key={yr}><h3>{yr}</h3><div>{researchTimeline.filter(t=>t.year===yr&&(region==='全部'||t.region===region)).map(t=><article key={t.title} className={t.region==='国内'?'domestic':'international'}><div><span>{t.region} · {t.type}</span><time>{t.date}</time></div><h4>{t.title}</h4><p>{t.body}</p><a href={t.url} target="_blank" rel="noopener noreferrer">{t.source} ↗</a></article>)}</div></section>)}</div></section>
 <section className="rl-note"><h3>这两张证据，怎样放进开题逻辑？</h3><p>时间线支持“议题持续进入科学评估与治理”；折线图支持“在明确数据库和检索式下，相关概括术语的文献出现比例长期上升”。接下来仍需证明：你的目标受众在哪个具体问题上理解困难，现有科普如何不足，以及设计能改善什么。</p><p>国内中文文献的年度趋势尚未统计。要与国际数据库比较，需要另行取得知网或万方同一检索式、同一年度范围的数据及分母；本页不会用精选政策数量代替国内文献频率。</p></section>
 </div>;
}
