import { useState, useEffect, type ReactNode } from 'react';
import { ArrowRight, Download, ExternalLink } from 'lucide-react';
import { planCases, caseConclusion } from './researchPlanCases';
import { planDate, scopeTitle, scope, argument, learningGoals, studySteps, hypotheses, rubric, schedule, conceptA, conceptB, planSources, readingCandidate, innovations, buildPlanMarkdown } from './researchPlanData';
import './research-plan.css';

const sourceUrl = (index: number) => planSources[index][2];
const outcomes = ['材料与纺织设计：关注源头释放', '废水处理：控制进入水环境的颗粒', '污泥及后续管理：继续关注被截留颗粒的去向'];
function SourceLink({ index, children }: { index:number; children?: ReactNode }) { return <a href={sourceUrl(index)} target="_blank" rel="noopener noreferrer">{children || planSources[index][1]} <ExternalLink size={12}/></a>; }
function Prototype() {
  const [concept, setConcept] = useState<'A'|'B'>('A');
  const [screen, setScreen] = useState(0);
  const [node, setNode] = useState(0);
  const [evidence, setEvidence] = useState(false);
  const [actor, setActor] = useState(0);
  const [choice, setChoice] = useState<number|null>(null);
  const [riskChoice, setRiskChoice] = useState<number|null>(null);
  const [riskFeedback, setRiskFeedback] = useState(false);
  const [transfer, setTransfer] = useState('');
  const [showGuide, setShowGuide] = useState(false);
  const frames = concept === 'A' ? conceptA : conceptB;
  const reset = () => { setScreen(0); setNode(0); setEvidence(false); setActor(0); setChoice(null); setRiskChoice(null); setRiskFeedback(false); setTransfer(''); setShowGuide(false); };
  return <div className="rp-prototypes">
    <div className="rp-concept-tabs" aria-label="选择设计概念">
      <button aria-pressed={concept==='A'} onClick={()=>{setConcept('A');setScreen(0);}}>A · 沿着一根纤维<small>按路径逐步理解</small></button>
      <button aria-pressed={concept==='B'} onClick={()=>{setConcept('B');setScreen(0);}}>B · 这条判断有依据吗<small>先判断，再解释</small></button>
    </div>
    <div className="rp-screen-nav" aria-label="关键界面草图">{frames.map((f,i)=><button key={f[0]} onClick={()=>setScreen(i)} aria-current={screen===i?'step':undefined}><span>0{i+1}</span>{f[0]}</button>)}</div>
    <div className="rp-demo-grid"><div className="rp-wireframe" aria-label={`${concept}方案第${screen+1}屏`}>
      <div className="rp-wireframe-top"><span>微塑料 / 一次洗涤之后</span><span>{screen+1} / 4</span></div>
      <div className="rp-screen" key={`${concept}-${screen}`}>
        {concept==='A' && screen===0 && <><span className="rp-overline">从身边的一件事开始</span><h3>衣服洗干净了，<br/>细小纤维去了哪里？</h3><div className="rp-laundry" aria-label="衣物、洗涤和排水的概念示意"><span>合成纤维<br/>衣物</span><ArrowRight/><span>洗涤</span><ArrowRight/><span>排水</span></div><p>研究发现，某些合成纤维织物在洗涤时会释放细小纤维。释放情况与织物及洗涤条件有关。</p><p className="rp-small">这里只看一个来源示例。不是所有纤维都是塑料，也不是所有微塑料都来自衣物。</p><SourceLink index={3}/></>}
        {concept==='A' && screen===1 && <><span className="rp-overline">点击节点，查看联系</span><h3>它的去向可能分支。</h3><div className="rp-nodes">{['合成纤维衣物','洗涤与释放','废水与处理','可能的后续去向'].map((n,i)=><button key={n} onClick={()=>setNode(i)} aria-pressed={node===i}><small>0{i+1}</small>{n}</button>)}</div><div className="rp-explanation" aria-live="polite"><b>{['先分清材料','释放需要具体条件','处理不是“凭空消失”','去向取决于具体系统'][node]}</b><p>{['这里讨论塑料材质的合成纤维；“纤维”描述形态，不能只凭形状确认材质。','部分纤维可能在洗涤过程中进入废水；不把某次实验的颗粒数量套到所有衣物。','废水收集与处理条件影响颗粒去向。可能有颗粒随出水进入环境，也有颗粒被截留并进入污泥等环节。','部分随出水进入水环境；被截留的部分还需关注污泥处理与处置。图中不设比例，也不表示所有颗粒必然到达海洋。'][node]}</p></div><p className="rp-small">以下以废水进入处理系统为例；未接入处理等其他路径未画出。</p><div className="rp-branches"><span>可能随出水 → 水环境</span><span>可能被截留 → 后续处理与处置</span></div><SourceLink index={5}/></>}
        {concept==='A' && screen===2 && <><span className="rp-overline">把结论与条件一起看</span><h3>知道了路径，<br/>还不能推出什么？</h3><div className="rp-switch"><button aria-pressed={!evidence} onClick={()=>setEvidence(false)}>已有依据</button><button aria-pressed={evidence} onClick={()=>setEvidence(true)}>推断的边界</button></div><div className="rp-explanation" aria-live="polite"><p>{evidence?'这张路径图没有个人接触量、颗粒特征或健康结局的信息，不能据此判断某个人一定受害，也不能给某件衣服计算健康风险。':'特定合成纤维织物洗涤可以释放细小纤维；废水及污泥管理是需要关注的环节。这些关系不等于每件物品的实测排放。'}</p></div><SourceLink index={evidence?2:3}/>{!evidence&&<SourceLink index={5}/>}<p className="rp-small">专业报告仍需结合研究对象、方法和年代阅读；后续正式内容将请相关专业人士核验。</p></>}
        {concept==='A' && screen===3 && <><span className="rp-overline">行动要能对应一个环节</span><h3>哪些人，可以在哪一步介入？</h3><div className="rp-actors">{outcomes.map((a,i)=><button key={a} onClick={()=>setActor(i)} aria-pressed={actor===i}>{a}</button>)}</div><div className="rp-explanation" aria-live="polite"><p>{['材料与纺织领域可研究怎样减少释放。需要依据实际测试评价设计和材料，不能仅凭“天然”“环保”等标签断定总体影响。','废水收集和处理可作用于迁移环节；措施效果与具体工艺和条件有关，不能把处理画成100%消失。','颗粒被截留后仍需要追踪后续管理。消费者、生产者与治理机构的作用不同，不能把责任都交给个人。'][actor]}</p></div><SourceLink index={4}/><p className="rp-small">尝试用自己的话解释：一项措施对应哪个环节？还有什么条件需要核查？</p></>}
        {concept==='B' && screen===0 && <><span className="rp-overline">先保留你的判断</span><h3>细小纤维进入废水后，<br/>可能发生什么？</h3><p>想象一次合成纤维衣物洗涤。先选择最接近你当前理解的说法。</p><fieldset className="rp-options"><legend>你的判断</legend>{['处理后必然全部消失','可能随出水或被截留，后续去向取决于条件','我还不确定'].map((c,i)=><label key={c}><input type="radio" name="path-prediction" checked={choice===i} onChange={()=>setChoice(i)}/><span>{c}</span></label>)}</fieldset><button className="rp-primary" disabled={choice===null} onClick={()=>setScreen(1)}>查看解释 <ArrowRight size={15}/></button><p className="rp-small">允许不确定。演示选择只在当前页面临时保留，不上传为研究数据。</p></>}
        {concept==='B' && screen===1 && <><span className="rp-overline">反馈说明“为什么”</span><h3>{choice===null?'先看这条关系':choice===0?'处理后，还需要追踪去向':choice===1?'还要把“取决于什么”说清楚':'不确定的地方，可以逐步核查'}</h3><div className="rp-explanation"><p>废水收集与处理条件影响颗粒去向。部分可能随出水进入环境，部分被截留后进入污泥等环节；具体比例与后续去向需有对应资料。</p></div><p className="rp-small">以下以废水进入处理系统为例；未接入处理等其他路径未画出。</p><div className="rp-branches"><span>可能随出水 → 水环境</span><span>可能被截留 → 后续处理与处置</span></div><p>“被截留”描述的是转移到另一个环节，不能直接理解为物质已经消失。</p><SourceLink index={5}/></>}
        {concept==='B' && screen===2 && <><span className="rp-overline">分清材料能回答的问题</span><h3>“某水样检出微塑料”，<br/>就能判断个人健康风险吗？</h3><fieldset className="rp-options"><legend>选择后再看解释</legend>{['能，检出就代表个人必然受到伤害','不能直接判断，还需要接触与影响等证据','不知道，还需要更多解释'].map((c,i)=><label key={c}><input type="radio" name="risk-prediction" checked={riskChoice===i} onChange={()=>{setRiskChoice(i);setRiskFeedback(false);}}/><span>{c}</span></label>)}</fieldset><button className="rp-primary" disabled={riskChoice===null} onClick={()=>setRiskFeedback(true)}>查看判断依据</button>{riskFeedback&&<div className="rp-explanation" role="status"><p>{riskChoice===0?'需要修正的是从“检出”直接跳到“必然伤害”这一步。':riskChoice===1?'关键是说明缺了哪些条件，而不仅记住“不能”。':'可以从证据缺口开始理解。'} 检出描述样品中的发现；个人风险还涉及颗粒特征、接触方式与量、时间及影响证据。</p><SourceLink index={2}/></div>}</>}
        {concept==='B' && screen===3 && <><span className="rp-overline">把关系带到一个新场景</span><h3>换成一个塑料餐盒，<br/>你会先查什么？</h3><p>这里只给出物品名称，没有检测结果。请写下你想核查的来源、释放条件、可能去向与证据，不必假定它一定释放了微塑料。</p><label className="rp-answer">你的解释<textarea value={transfer} onChange={e=>setTransfer(e.target.value)} maxLength={1500} placeholder="我还需要知道……；如果……，才可能……"/></label><button className="rp-text-button" onClick={()=>setShowGuide(!showGuide)} aria-expanded={showGuide}>{showGuide?'收起思考提示':'查看思考提示'}</button>{showGuide&&<div className="rp-explanation"><p>可先核查材质和使用条件，是否有适用的释放证据，再讨论颗粒可能进入何种介质。不能仅凭物品名称推断排放量或个人伤害。开放解释需要人工结合科学依据评价。</p></div>}<p className="rp-small">这是界面演示；输入不上传、刷新后清除。正式测试需另行固定材料和评分规则。</p></>}
      </div>
      <div className="rp-demo-controls"><button disabled={screen===0} onClick={()=>setScreen(screen-1)}>上一屏</button><button onClick={reset}>重新体验</button><button disabled={screen===3} onClick={()=>setScreen(screen+1)}>下一屏</button></div>
    </div><aside className="rp-design-note"><span className="rp-overline">这一屏为什么这样设计</span><h3>{frames[screen][0]}</h3><p>{frames[screen][1]}</p><h4>后续观察什么</h4><p>{frames[screen][2]}</p><h4>构想的适用条件</h4><p>{concept==='A'?'当困难主要是关系断裂、路径跳跃时优先尝试；若点击分散注意或图文已经足够，应简化呈现。':'当用户的判断与理由需要显露和修正时尝试；避免变成只追求答对的题库，解释与迁移才是核心。'}</p><p className="rp-small">低保真概念 · 不是实验定稿<br/>无实测排放比例或健康风险分数</p></aside></div>
    <div className="rp-frame-list">{frames.map((f,i)=><article key={f[0]}><span>0{i+1}</span><h4>{f[0]}</h4><p>{f[1]}</p></article>)}</div>
  </div>;
}
function downloadPlan() { const url=URL.createObjectURL(new Blob([buildPlanMarkdown()],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`新污染物-研究与设计准备稿-${planDate}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
export default function ResearchPlan() {
  useEffect(()=>{const hash=window.location.hash; if(/^#plan-[a-z]+$/.test(hash)){const id=requestAnimationFrame(()=>document.getElementById(hash.slice(1))?.scrollIntoView());return ()=>cancelAnimationFrame(id);}},[]);
  return <div className="rl-content rp-content">
    <section className="rp-intro"><span className="rl-label">从背景依据，走向可研究的设计问题 · {planDate}</span><h2>下一次见导师，带着这些具体材料。</h2><p>暂定范围、调研工具、六个案例、两套四屏构想，以及验证与时间安排。先把方案说清楚，再用真实受众的记录决定怎样收窄。</p><div className="rp-state"><span>已准备：方案与草图</span><span>待开展：访谈、专业核验与测试</span></div><div className="rp-downloads"><button onClick={downloadPlan}><Download size={15}/>下载完整准备稿</button><a href="/graduation/review">阅读导师讨论稿 <ExternalLink size={14}/></a></div></section>
    <nav className="rp-jumps" aria-label="方案内容"><a href="#plan-scope">01 暂定选题</a><a href="#plan-study">02 用户调研</a><a href="#plan-cases">03 案例比较</a><a href="#plan-concepts">04 两套构想</a><a href="#plan-test">05 验证与安排</a></nav>
    <section id="plan-scope" className="rp-section"><span className="rp-overline">01 / 一页选题说明</span><h2>{scopeTitle}</h2><p className="rp-caption">工作题名 · 供导师讨论，尚未定题</p><dl className="rp-scope">{scope.map(([label,body])=><div key={label}><dt>{label}</dt><dd>{body}</dd></div>)}</dl>
      <div className="rp-argument">{argument.map(([title,because,therefore,status],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p><b>因为</b>{because}</p><p><b>所以</b>{therefore}</p><small>{status}</small></article>)}</div>
      <h3 className="rp-subtitle">具体科普什么，学会什么</h3><div className="rp-table-scroll"><table><thead><tr><th>内容</th><th>科普重点</th><th>可观察的理解目标</th></tr></thead><tbody>{learningGoals.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div>
    </section>
    <section id="plan-study" className="rp-section"><span className="rp-overline">02 / 可以开始执行的首轮研究</span><h2>先听、再看、再解释。</h2><p>首轮拟招募6—8名年满18岁的非环境专业在校大学生，每人约28分钟。尽量涵盖不同专业、阶段与相关学习经历；这是探索安排，不代表全体大学生。先用1名志愿者试走流程，调整后固定脚本版本。</p><div className="rp-downloads"><a href="/research/2026-09-22-interview-guide.md" download><Download size={15}/>访谈指南与招募文字</a><a href="/research/2026-09-22-interview-record.csv" download><Download size={15}/>逐人记录空表</a><a href="/research/2026-09-22-findings-record.csv" download><Download size={15}/>问题归纳空表</a></div>
      <div className="rp-protocol">{studySteps.map(([time,title,body])=><article key={title}><time>{time}</time><div><h3>{title}</h3><p>{body}</p></div></article>)}</div>
      <div className="rp-callout"><h3>开始访谈前，备好这三件事</h3><ol><li>固定一份经过内容核验、语言与长度合适的现有中文科普材料，保存原文、日期与版本。本页草图用于方案讨论，不作为首轮现有材料。</li><li>空白画图纸和记录表；先保存基线，再出示材料。不要为得到完整路径不断提示。</li><li>确认参加与录音意愿；用编号记录。联系方式、录音及原始记录另行保管，不上传到这个公开页面。保存期限与撤回联系渠道需在招募前填写。</li></ol><p>本轮需要发现实际困难，也允许发现“已经理解”“现有材料足够”或“需求并不在这里”。目前没有受访者数据。</p></div>
      <details className="rp-method"><summary>已找到的首轮中文阅读候选与使用范围</summary><p><a href={readingCandidate.url} target="_blank" rel="noopener noreferrer">{readingCandidate.title}</a> · {readingCandidate.date}</p><p>{readingCandidate.range}</p><p>{readingCandidate.limit}</p><p>这是供试访选择的材料，先核对截取范围和任务是否匹配；不会把未被材料解释的知识当作读者应该学会的内容。</p></details>
      <h3 className="rp-subtitle">怎样从记录走到设计</h3><div className="rp-table-scroll"><table><thead><tr><th>条件式假设</th><th>需要真实证据</th><th>可能的回应</th><th>怎样检验</th></tr></thead><tbody>{hypotheses.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><p className="rp-caption">未提及不等于不知道；担忧不等于理解错误。记录原话与研究者解释时分栏填写，保留反例。</p>
    </section>
    <section id="plan-cases" className="rp-section"><span className="rp-overline">03 / 同一组维度，比较六个真实案例</span><h2>已有实践做到了哪里？</h2><p>4个国外案例、2个国内活动案例。下面是公开材料分析，核读范围逐项注明；没有实际参加活动或完成用户效果测试。</p><div className="rp-case-list">{planCases.map(c=><details key={c.id}><summary><span>{c.region}</span><strong>{c.name}</strong><span className="rp-plus">＋</span></summary><div className="rp-case-body"><dl>{[['内容与形式',c.content],['操作与反馈',c.interaction],['本轮核读范围',c.access],['对本研究的启发',c.lesson],['还需验证',c.question]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="rp-links">{c.links.map(l=><a key={l.url} href={l.url} target="_blank" rel="noopener noreferrer">{l.label}<ExternalLink size={12}/></a>)}</div></div></details>)}</div><div className="rp-callout"><h3>这对“创新点”意味着什么</h3><p>{caseConclusion}</p></div></section>
    <section id="plan-concepts" className="rp-section"><span className="rp-overline">04 / 两套可点击的关键界面草图</span><h2>先让导师看到“准备怎样做”。</h2><p>以同一个衣物洗涤情境探索两种组织方式。点击四个步骤查看草图与设计理由。内容是示范，正式原型将随调研和专业核验修订。</p><Prototype/>
      <h3 className="rp-subtitle">拟探索的贡献</h3><div className="rp-three">{innovations.map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><p className="rp-caption">这里写的是待验证的贡献方向。“用了交互”“加了答题”“做了动画”本身不构成已证实的创新。</p>
      <div className="rp-callout"><h3>作品载体与可行性</h3><p>暂定网页交互原型：一个核心生活情境、路径模块、证据说明、治理关系与迁移任务。手机和电脑都能打开，展览时可复用为触屏内容。当前草图已能切换和提供反馈，说明演示可实现；学习效果仍待验证。</p><p>首版不依赖实时监测、硬件传感器或自动健康判断。正式研究还需统一刺激材料、专家核验和匿名评价记录；如果调研显示必须依靠触觉或空间体验，再评估装置成本和展陈条件。</p></div>
    </section>
    <section id="plan-test" className="rp-section"><span className="rp-overline">05 / 用什么证据判断设计有帮助</span><h2>看解释是否变好，也看是否能迁移。</h2><div className="rp-three"><article><h3>先做可用性试测</h3><p>观察操作、信息查找和新误解。同一人看两版时交替顺序；学习会影响后续表现，这一轮不直接宣称哪版效果更好。</p></article><article><h3>再做内容相当的比较</h3><p>统一科学内容、语言难度、证据、可读性及任务。若要判断交互是否有价值，需要加入图文条件；A与B比较本身不能回答这个问题。</p></article><article><h3>以理解任务为主</h3><p>解释路径、辨别证据、联系治理，尤其观察新情境迁移。满意度、用时和点击仅作辅助；条件允许时增加延后复测。</p></article></div>
      <h3 className="rp-subtitle">工作性评分草案</h3><p className="rp-caption">研究者拟定的记录工具，不是已验证量表。正式使用前核验科学答案、评分例子与情境适用性。</p><div className="rp-table-scroll"><table><thead><tr><th>维度</th><th>0分</th><th>1分</th><th>2分</th></tr></thead><tbody>{rubric.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><p className="rp-caption">0分另标“未回答／不知道／明确错误”，不混淆不确定与错误断言。不设及格线；请第二位研究者核对部分评分，讨论分歧。</p>
      <details className="rp-method"><summary>导师提到的定量研究，怎样接上？</summary><p>先依据访谈决定是否需要问卷及测什么，把“自认为了解”与实际理解题分开，保留“不知道”并进行预测试。正式样本量根据主要指标、比较方式及精度要求或试测信息确定，不先凭空指定代表性人数。</p><p>本轮可报告“参与的8人中有3人出现某情况”，不能写成“37.5%的大学生存在该问题”。正式原型比较另行制定分组、主要指标、样本量依据和分析计划。</p></details>
      <h3 className="rp-subtitle">到11月13日，按成果推进</h3><div className="rp-schedule">{schedule.map(([date,title,body])=><article key={date}><time>{date}</time><div><h3>{title}</h3><p>{body}</p></div></article>)}</div><div className="rp-callout"><h3>开题时应当拿出的东西</h3><p>问题依据、真实探索记录、案例对照、选定的设计逻辑与草图，以及后续测试计划。毕业创作预期再形成完整原型、对照材料、评价记录、研究报告与展陈说明。</p><p><strong>最近的一步：</strong>带这一页范围和两套草图与导师讨论，同时准备首轮招募。真实参与者的回答将决定下一版，空表不等于已经完成了用户研究。</p></div>
    </section>
    <section className="rp-section rp-source-section"><h3>本方案与草图的科学、研究来源</h3><p className="rp-caption">案例原文见各案例卡片。其余文献可在“全部资料”栏目继续核读。</p>{planSources.map(([type,title,url,note])=><div key={url}><span>{type}</span><a href={url} target="_blank" rel="noopener noreferrer">{title}<ExternalLink size={12}/></a><p>{note}</p></div>)}</section>
  </div>;
}
