import {lazy, Suspense, useEffect, useMemo, useRef, useState} from 'react';
import {Link, useLocation, useNavigate} from 'react-router-dom';
import {ArrowLeft, ArrowUpRight, BookOpen, ChevronLeft, ChevronRight, Grid2X2, List, Search, Shuffle, X} from 'lucide-react';
import {MobileCanvas, MobileDialog, MobileImage, ImageViewer} from '../mobile/MobileMedia';
import {displayDate, fileSize, localized, type CanvasLayout} from '../mobile/types';
import {resolveRuntimeContentUrl} from '../runtimeUrls';
import './collections.css';
const PdfReader=lazy(()=>import('../mobile/MobilePdfReader'));
export type CollectionKind='pdfs'|'vibecoding'|'journal';
type Item={id:string;title:string;titleZh?:string;titleEn?:string;description?:string;descriptionZh?:string;descriptionEn?:string;note?:string;date?:string;updatedAt?:string;createdAt?:string;coverImage?:string;fileUrl?:string;size?:number;pageCount?:number;slug?:string;layout?:CanvasLayout;workEntryIds?:string[]};
const config={
 pdfs:{label:['作品集','Portfolio'],title:['把创作，装订成册。','A collection of perspectives.'],note:['从封面开始，慢慢翻进一个想法。','Start with a cover. Stay for the ideas.'],tag:'THE READING ROOM',endpoint:'/api/pdfs',key:'pdfs'},
 vibecoding:{label:['实验','Experiments'],title:['好奇心，可以玩。','Curiosity, at your fingertips.'],note:['一些关于影像、空间和交互的小实验。点开，就能亲自试试。','Small experiments in images, space and interaction. Step inside and try.'],tag:'THE PLAY ROOM',endpoint:'/api/vibecoding',key:'projects'},
 journal:{label:['手账','Journal'],title:['让日常，多停一会儿。','Everyday, worth keeping.'],note:['照片、片段，还有那一天没说完的话。','Photographs, little moments, and words left over from the day.'],tag:'THE EVERYDAY ROOM',endpoint:'/api/journals',key:'journals'},
};
const paths={pdfs:'/pdfs',vibecoding:'/vibecoding',journal:'/journal'};
function timestamp(item:Item){const raw=item.date||item.updatedAt||item.createdAt||'';const parts=raw.match(/^(\d{4})[-./](\d{1,2})(?:[-./](\d{1,2}))?/);return parts?new Date(+parts[1],+parts[2]-1,+(parts[3]||1)).getTime():Date.parse(raw)||0;}
const yearOf=(item:Item)=>(item.date||item.updatedAt||item.createdAt||'').match(/^\d{4}/)?.[0]||'';
export default function CollectionPage({kind,lang,onToggleLang}:{kind:CollectionKind;lang:'zh'|'en';onToggleLang:()=>void}){
 const cfg=config[kind], t=(zh:string,en:string)=>localized(lang,zh,en), location=useLocation(),navigate=useNavigate();
 const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 const [query,setQuery]=useState(''),[year,setYear]=useState('all'),[sort,setSort]=useState('new'),[view,setView]=useState('gallery'),[page,setPage]=useState(1),[notice,setNotice]=useState(''),[image,setImage]=useState<string|null>(null);
 const listRef=useRef<HTMLElement>(null),noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const focus=new URLSearchParams(location.search).get('focus');
 const title=(item:Item)=>localized(lang,item.titleZh||item.title,item.titleEn);
 const description=(item:Item)=>localized(lang,item.descriptionZh||item.description||item.note,item.descriptionEn);
 const cover=(item:Item)=>resolveRuntimeContentUrl(item.coverImage||item.layout?.elements?.find(e=>e.type==='image')?.url||'');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError(false);fetch(cfg.endpoint,{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data[cfg.key]))throw Error();setItems(data[cfg.key]);setPage(1);}).catch(e=>{if(e.name!=='AbortError')setError(true);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[cfg.endpoint,retry]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});document.body.classList.add('collection-mode');return()=>document.body.classList.remove('collection-mode');},[kind]);
 useEffect(()=>{document.querySelector('.co-dialog')?.scrollTo({top:0,behavior:'instant'});},[focus]);
 useEffect(()=>()=>{if(noticeTimer.current)clearTimeout(noticeTimer.current);},[]);
 const filtered=useMemo(()=>items.filter(i=>(year==='all'||yearOf(i)===year)&&`${title(i)} ${description(i)}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).sort((a,b)=>sort==='title'?title(a).localeCompare(title(b),lang):sort==='old'?timestamp(a)-timestamp(b):timestamp(b)-timestamp(a)),[items,query,year,sort,lang]);
 const years=[...new Set(items.map(yearOf).filter(Boolean))].sort().reverse();
 const active=items.find(i=>i.id===focus),activeIndex=filtered.findIndex(i=>i.id===focus),pages=Math.max(1,Math.ceil(filtered.length/12));
 const featured=[...items].sort((a,b)=>timestamp(b)-timestamp(a))[0];
 function open(item:Item){navigate(`${paths[kind]}?focus=${encodeURIComponent(item.id)}`,{replace:!!focus});}
 function close(){navigate(paths[kind],{replace:true});}
 function reset(){setQuery('');setYear('all');setPage(1);}
 function showNotice(message:string){setNotice(message);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),2400);}
 async function copyLink(){try{await navigator.clipboard.writeText(window.location.href);showNotice(t('链接已复制','Link copied'));}catch{showNotice(t('请复制浏览器地址分享','Copy the address from your browser to share'));}}
 function surprise(){if(filtered.length){const choices=filtered.filter(i=>i.id!==focus);open((choices.length?choices:filtered)[Math.floor(Math.random()*(choices.length||filtered.length))]);}}
 const date=(i:Item)=>displayDate(i.date||i.updatedAt||i.createdAt,lang);
 const action=t(kind==='pdfs'?'开始阅读':kind==='journal'?'翻开这一页':'了解实验',kind==='pdfs'?'Start reading':kind==='journal'?'Open this memory':'Explore experiment');
 return <div className={`co-page co-${kind} no-grass`} lang={lang==='zh'?'zh-CN':'en'}>
  <header className="co-nav"><Link to="/" className="co-back"><ArrowLeft size={17}/><span>Gemos.</span></Link><nav aria-label={t('栏目导航','Collection navigation')}>{(Object.keys(config) as CollectionKind[]).map(k=><Link key={k} to={paths[k]} aria-current={k===kind?'page':undefined}>{t(...config[k].label as [string,string])}</Link>)}</nav><button onClick={onToggleLang} aria-label={t('切换语言','Switch language')}>{lang==='zh'?'EN':'中'}</button></header>
  <main className="co-main">
   <section className="co-intro"><div><p className="co-eyebrow">{cfg.tag}</p><h1>{t(...cfg.title as [string,string])}</h1><p className="co-lead">{t(...cfg.note as [string,string])}</p><div className="co-intro-bottom"><span>{loading?'—':items.length} {t(kind==='pdfs'?'本作品集':kind==='journal'?'页生活':'个可玩的想法',kind==='pdfs'?'publications':kind==='journal'?'memories':'playable ideas')}</span><button disabled={!filtered.length||loading||error} onClick={surprise}><Shuffle size={15}/>{t(kind==='journal'?'偶遇一页':'随手翻一个',kind==='journal'?'A chance memory':'Surprise me')}</button></div></div>
    {featured&&!error?<button className="co-feature" onClick={()=>open(featured)} aria-label={`${action} · ${title(featured)}`}><div className="co-feature-art"><MobileImage src={cover(featured)} alt={title(featured)} priority/></div><div className="co-feature-caption"><small>{t('最近收录','LATEST ADDITION')}</small><strong>{title(featured)}</strong><span>{action}<ArrowUpRight size={16}/></span></div></button>:<div className="co-intro-placeholder" aria-hidden="true"><BookOpen size={70} strokeWidth={.7}/></div>}
   </section>
   <section ref={listRef} className="co-collection" aria-label={t('浏览全部','Browse collection')}>
    <div className="co-toolbar"><label className="co-search"><Search size={17}/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder={t('搜索标题或文字','Search titles or words')} aria-label={t('搜索内容','Search collection')}/>{query&&<button onClick={()=>{setQuery('');setPage(1);}} aria-label={t('清空搜索','Clear search')}><X size={15}/></button>}</label><div className="co-tools"><select value={year} onChange={e=>{setYear(e.target.value);setPage(1);}} aria-label={t('按年份筛选','Filter by year')}><option value="all">{t('全部年份','All years')}</option>{years.map(y=><option key={y}>{y}</option>)}</select><select value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}} aria-label={t('排序方式','Sort order')}><option value="new">{t('最新在前','Newest first')}</option><option value="old">{t('最早在前','Oldest first')}</option><option value="title">{t('按标题','Title')}</option></select><div className="co-view" role="group" aria-label={t('浏览方式','View mode')}><button aria-label={t('画廊视图','Gallery view')} aria-pressed={view==='gallery'} onClick={()=>setView('gallery')}><Grid2X2 size={17}/></button><button aria-label={t('目录视图','List view')} aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={18}/></button></div></div></div>
    <div className="co-result" role="status">{loading?t('正在整理内容…','Gathering the collection…'):error?'':`${filtered.length} ${t('条内容','items')}`}{(query||year!=='all')&&<button onClick={reset}>{t('重置筛选','Reset filters')}</button>}</div>
    {loading?<div className="co-skeleton" aria-label={t('加载中','Loading')}>{[0,1,2].map(n=><div key={n}/>)}</div>:error?<div className="co-empty" role="alert"><h2>{t('暂时没能加载','Could not load this collection')}</h2><p>{t('请稍后再试一次。','Please try again.')}</p><button onClick={()=>setRetry(n=>n+1)}>{t('重新载入','Try again')}</button></div>:!filtered.length?<div className="co-empty"><BookOpen size={32} strokeWidth={1}/><h2>{items.length?t('没有找到这条内容','No matches'):t('给下一次记录，留一点位置。','A little room for what comes next.')}</h2>{items.length>0&&<button onClick={reset}>{t('查看全部','Show everything')}</button>}</div>:<div className={`co-grid is-${view}`}>{filtered.slice((page-1)*12,page*12).map((item,index)=><article className="co-card" key={item.id}>
     <button className="co-card-open" onClick={()=>open(item)} aria-label={`${action} · ${title(item)}`}><div className="co-card-art"><MobileImage src={cover(item)} alt={title(item)}/><span className="co-card-number">{String((page-1)*12+index+1).padStart(2,'0')}</span><span className="co-card-peek"><ArrowUpRight size={19}/></span></div><div className="co-card-copy"><p className="co-card-date">{date(item)||t('未注明日期','Undated')}</p><h2>{title(item)}</h2><p className="co-card-note">{description(item)||t(kind==='pdfs'?'翻开，看看这一阶段的创作。':kind==='journal'?'一个值得留下的瞬间。':'点开试试，会发生什么。',kind==='pdfs'?'A chapter of creative work.':kind==='journal'?'A moment worth keeping.':'Step inside and see what happens.')}</p></div></button>
     <div className="co-card-footer">{kind==='vibecoding'&&item.slug==='still-memory-box'?<a href="/gemos-still/">{t('Mac 原生版','Native Mac app')}<ArrowUpRight size={14}/></a>:null}<span>{kind==='pdfs'?`${fileSize(item.size)}${item.pageCount?` · ${item.pageCount} ${t('页','pages')}`:''}`:kind==='journal'?t('生活片段','A moment in life'):t('交互实验','Interactive experiment')}</span>{kind==='vibecoding'&&item.slug?<a href={`/vibecoding/${encodeURIComponent(item.slug)}`} target="_blank" rel="noopener noreferrer">{t('直接试玩','Play now')}<ArrowUpRight size={14}/></a>:<button onClick={()=>open(item)}>{action}<ChevronRight size={14}/></button>}</div>
    </article>)}</div>}
    {pages>1&&<div className="co-pagination"><button disabled={page===1} onClick={()=>{setPage(p=>p-1);listRef.current?.scrollIntoView({behavior:'smooth'});}}><ChevronLeft size={17}/>{t('上一页','Previous')}</button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>{setPage(p=>p+1);listRef.current?.scrollIntoView({behavior:'smooth'});}}>{t('下一页','Next')}<ChevronRight size={17}/></button></div>}
   </section>
   <footer className="co-footer"><span>GemosDodo / {t(...cfg.label as [string,string])}</span><Link to="/">{t('回到首页','Back home')}<ArrowUpRight size={14}/></Link></footer>
  </main>
  {focus&&!loading&&!error&&!active&&<MobileDialog label={t('内容不可用','Content unavailable')} onClose={close} className="co-dialog"><div className="co-empty"><h2>{t('这条内容不在这里了','This item is no longer here')}</h2><button onClick={close}>{t('返回浏览','Back to collection')}</button></div></MobileDialog>}
  {active&&<MobileDialog label={title(active)} onClose={close} className={`co-dialog co-detail-${kind}`}><header className="co-reader-bar"><span>{t(...cfg.label as [string,string])}</span><div><span className="co-reader-notice" role="status">{notice}</span><button onClick={copyLink}>{t('分享','Share')}</button><button onClick={close} aria-label={t('关闭详情','Close details')}><X size={21}/></button></div></header><div className="co-detail-body" key={active.id}><div className="co-detail-intro"><p className="co-eyebrow">{date(active)}</p><h2>{title(active)}</h2>{description(active)&&<p>{description(active)}</p>}{kind==='pdfs'&&active.fileUrl&&<a className="co-primary" href={active.fileUrl} target="_blank" rel="noopener noreferrer">{t('打开原文件','Open original PDF')}<ArrowUpRight size={16}/></a>}</div>
    {kind==='pdfs'&&active.fileUrl&&<Suspense fallback={<p className="co-empty">{t('正在准备阅读…','Preparing your document…')}</p>}><PdfReader url={active.fileUrl} lang={lang}/></Suspense>}
    {kind==='journal'&&(active.layout?.elements?.length?<MobileCanvas layout={active.layout} lang={lang} onImage={setImage}/>:<MobileImage src={cover(active)} alt={title(active)} priority/>)}
    {kind==='vibecoding'&&<><MobileImage src={cover(active)} alt={title(active)} className="co-experiment-cover" priority/>{active.slug&&<a className="co-primary co-launch" href={`/vibecoding/${encodeURIComponent(active.slug)}`} target="_blank" rel="noopener noreferrer">{t('进入实验，亲自试试','Step inside and play')}<ArrowUpRight size={18}/></a>}{active.slug==='still-memory-box'&&<a className="co-primary co-launch" style={{marginLeft:12}} href="/gemos-still/">{t('了解并下载 Mac 版','Explore the Mac app')}<ArrowUpRight size={18}/></a>}</>}
    {!!active.workEntryIds?.length&&<div className="co-related"><h3>{t('相关作品','Related work')}</h3>{active.workEntryIds.map((id,i)=><Link to={`/?work=${encodeURIComponent(id)}`} key={id}>{t('查看作品','View work')} {i+1}<ArrowUpRight size={14}/></Link>)}</div>}
   </div>{filtered.length>1&&<footer className="co-reader-next"><button disabled={activeIndex<=0} onClick={()=>open(filtered[activeIndex-1])}><ChevronLeft size={17}/>{t(kind==='pdfs'?'上一本':kind==='journal'?'上一页':'上一个','Previous')}</button><span>{activeIndex<0?'—':activeIndex+1} / {filtered.length}</span><button disabled={activeIndex<0||activeIndex>=filtered.length-1} onClick={()=>open(filtered[activeIndex+1])}>{t(kind==='pdfs'?'下一本':kind==='journal'?'下一页':'下一个','Next')}<ChevronRight size={17}/></button></footer>}</MobileDialog>}
  {image&&<ImageViewer src={image} title={active?title(active):''} lang={lang} onClose={()=>setImage(null)}/>}
  <div className="co-toast" role="status" aria-live="polite">{active?'':notice}</div>
 </div>;
}
